using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Networking;
using UnityEngine.SceneManagement;

public class GameManager : Singleton<GameManager>
{
    public SpriteRenderer[] door;
    public GameObject[] rooms;

    private int roomIndex = 0;
    public Sprite doorOpen;
    private JsonController _json;

    private UIManager _uIManager;

    private QuizManager _quizManager;
    private DialogueManager _dialogueManager;

    public bool isInteracting = false;
    private Movement player;
    private bool quizPassed = false;
    private bool lvl1QuizPassed = false;
    private bool lvl2QuizPassed = false;
    private bool lvl3QuizPassed = false;

    [SerializeField]
    private string BASE_URL = "https://docs.google.com/forms/u/0/d/e/1FAIpQLSdKmNRxpf0460uiCSEKMoheZodlUqtHkM8MCAEy4fGS3y_d-A/formResponse";


    void Awake()
    {

        if (GameManager.Instance != null && GameManager.Instance != this)
        {
            Destroy(this.gameObject);

        }
        else
        {
            DontDestroyOnLoad(this.gameObject);
        }


        //Generate the Instance of the Json Document.
        _json = this.gameObject.AddComponent<JsonController>();
        _json.GetJson();

        _uIManager = this.gameObject.GetComponent<UIManager>();
        _quizManager = this.gameObject.GetComponent<QuizManager>();
        _dialogueManager = this.gameObject.GetComponent<DialogueManager>();

    }

    public void OpenContentMenu(string id)
    {
        _uIManager.OpenContentMenu(id);
    }

    public void OpenQuizMenu(List<Questions> quiz,int level)
    {

        //_quizManager.StartQuiz(quiz);
        
        _uIManager.OpenQuizMenu(_quizManager,quiz,level);
    }


    public void CloseQuizMenu()
    {
        _uIManager.CloseQuizMenu();
    }

    public void OpenDialogue(string aName, List<Dialogue> convo,List<Questions> quiz, int level)
    {
        _dialogueManager.OpenDialogue(aName,convo,quiz,level);
    }

    public void CloseDialogue()
    {
        _dialogueManager.StopDialogue();
    }

    /*public GameObject GetNextRoom()
    {
        Debug.Log(roomIndex);
        return rooms[roomIndex];
    }
    */

    public QuizManager GetQuizManager()
    {
        return _quizManager;
    }
    public Movement GetPlayer()
    {
        return player;
    }

    public void DidPlayerPassQuiz(bool passed,int level)
    {
        if(passed == true)
        {
            if(level == 1)
            {
                lvl1QuizPassed = true;

            }
            else if( level == 2)
            {
                lvl2QuizPassed = true;

            }
            else if(level ==3)
            {
                lvl3QuizPassed = true;

            }

        }
        quizPassed = passed;
    }

    public bool GetPlayersQuizResults()
    {
        return quizPassed;
    }

    public bool GetPlayersQuizResultsLVL1()
    {
        return lvl1QuizPassed;
    }
    public bool GetPlayersQuizResultsLVL2()
    {
        return lvl2QuizPassed;
    }
    public bool GetPlayersQuizResultsLVL3()
    {
        return lvl3QuizPassed;
    }

    public void SetInteractingFalse()
    {
        isInteracting = false;
    }
    public void SetInteractingTrue()
    {
        isInteracting = true;
    }

    public bool GetInteraction()
    {
        return isInteracting;
    }

    /// <summary>
    /// Creates and sends the Analytics data to a google spreadsheet.
    /// </summary>
    /// <param name="timer"></param>
    /// <param name="interactions"></param>
    /// <param name="scorePercent"></param>
    /// <returns></returns>
    public IEnumerator CreateAnalyticsData(string timer, string interactions, string scorePercent)
    {
        WWWForm form = new WWWForm();
        form.AddField("entry.172307503", timer);
        form.AddField("entry.1592556701", interactions);
        form.AddField("entry.1050833444", scorePercent);
        byte[] rawData = form.data;
        //Updated this to UnityWebRequest as WWW is obsolete.
        using (var w = UnityWebRequest.Post(BASE_URL, form))
        {
            yield return w.SendWebRequest();
            if (w.isHttpError || w.isNetworkError)
            {
                Debug.Log(w.error);
            }
            else
            {
                Debug.Log("Finished Sending Analytics Data");
            }
        }

    }

    /// <summary>
    /// Get the Json Instance generated by the gamemanager and return it. 
    /// </summary>
    /// <returns>JsonController jsonObject</returns>
    public JsonController GetJson()
    {
        return _json;
    }

    // Start is called before the first frame update
    void Start()
    {
        isInteracting = false;
        player = GameObject.FindObjectOfType<Movement>();
        if (player == null)
        {
            Debug.Log("no player to interact with");
        }
    }
    
    /*public void SetRoomIndex(int index)
    {
        Debug.Log(index);
        roomIndex = index;
        Debug.Log(roomIndex);

    }
    */

    public void MovePlayerToRoom(int index)
    {
       player.transform.position = new Vector3(rooms[index].transform.position.x, rooms[index].transform.position.y, 0);

    }



    public void OpenDoors()
    {
        if(GetPlayersQuizResultsLVL1())
        {
            door[0].sprite = doorOpen;
            door[1].sprite = doorOpen;
        
        }
        if(GetPlayersQuizResultsLVL2())
        {
            door[2].sprite = doorOpen;
            door[3].sprite = doorOpen;
            
        }
        /*
        if(GetPlayersQuizResultsLVL3())
        {
            door[4].sprite = doorOpen;
        
        }
        */

    }

    // Update is called once per frame
    void Update()
    {

       
        OpenDoors();
    }
}
